config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :cars do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings, dependent: :destroy
  validates :brand, presence: true, length: { minimum: 3 }
  validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def new
    @car = Car.find(params[:car_id])
    @booking = Booking.new
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <h2>Mes réservations</h2>
    <% @bookings.each do |booking| %>
      <h3 class="home-offer-card-infos-name"><%= booking.car.brand %></h3>
      <p class="home-offer-card-infos-description"><%= booking.start_date %> - <%= booking.end_date %></p>
    <% end %>
</div>

app/views/bookings/new.html.erb
<div class="show-car-container">
    <h2 class="m-bold-title"><%= @car.brand.capitalize %></h2>
    <div class="show-car-card back-plate">
        <div class="show-car-card-details">
            <div class="show-car-card-infos">
                <h3 class="s-title"><%= "#{@car.brand.capitalize}" %></h3>
                <p class="show-card-address"><%= @car.address %></p>
                <p class="show-card-price-per-day"><b>$<%= @car.price %></b> /day</p>
            </div>

            <div class="show-card-book-section">
                <%= simple_form_for(@booking, url: car_bookings_path(@car)) do |f| %>
                    <p class="fsize4" id="from-label"></p>
                    <p class="fsize4" id="to-label"></p>
                    <p class="fsize4" id="recap-label"></p>

                    <%# Flatpickr's conatiner, with price_per_day and unavailables_dates values %>
                    <input type="string" placeholder="Select your dates" data-controller="flatpickr" data-flatpickr-array-value=<%= @unavailable_dates %> data-flatpickr-price-per-day-value=<%= @car.price %>>

                    <%# Simple_form inputs, where Flatipickr will put the dates %>
                    <%= f.input :start_date, as: :hidden, input_html: { data: { controller: "datepicker" }} %>
                    <%= f.input :end_date, as: :hidden, input_html: { data: { controller: "datepicker" } } %>

                    <%= f.submit 'Book now', class: 'main-cta m-bold-title' %>
                <% end %>
            </div>

        </div>
    </div>
    <%= link_to 'Back to cars', cars_path, class: 'secondary-cta' %>
</div>

app/views/cars/index.html.erb
<div class="container">
  <h1>Nos voitures</h1>
  <% @cars.each do |car| %>
    <%= car.brand %>
    <%= car.price %> SimpFlouz / jour
    <%= link_to "Voir le véhicule", car_path(car) %><br><br>
  <% end  %>
</div>

app/views/cars/show.html.erb
<div class="container">
  <h1><%= @car.brand %>
    <%= @car.price %> SimpFlouz / jour</h1>
    <%= @car.address %>
    <%= link_to "Réserver cette voiture", new_car_booking_path(@car) %><br>
    <%= link_to "Retour à la liste des voitures", cars_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExerciceLocationVoiture</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1>Bienvenu sur notre site de location de voitures entre particuliers</h1>
  <h2>C'est votre première visite?</h2>
  <p>Vous pouvez créer votre compte dès maintenant en cliquant sur le lien ci-dessous</p>
  <%= link_to "créer mon compte", new_user_registration_path %>
  <h2>Vous êtes déjà inscrit?</h2>
  <p>Vous pouvez consulter tous nos véhicules en cliquant sur le lien ci-dessous</p>
  <%= link_to "Voir les véhicules", cars_path(@cars) %>
</div>